pack: backtranslation_passages_dsk
reuse_completed: false
models:
  instruction_writer:
    endpoint: openai
    max_concurrency: 5
generation:
  min_article_chars: 400
  temperature: 1.0
  train_fraction: 0.9
sources:
  - name: odense
    source:
      path: dsk-odense.parquet
      text_field: text
      id_field: id
    generation:
      content_type: news
      max_articles: 1
  - name: danskerhverv
    source:
      path: dsk-danskerhverv.parquet
      text_field: text
      id_field: id
    generation:
      content_type: news
      max_articles: 1
